
const DeveloperList = [
    {
        id: 1,
        devImg: "https://snipboard.io/LTGtUW.jpg",
        devName: "Katharine Dean",
        devLocation: "802 Valle Verde Terrraces, Meralco Ave. Ext. 1600, Pasig City, Metro Manila",
        devMainRole: "UI/UX Designer",
        skillSet: "Full Time",
        skillSet2: "Sketch",
        skillSet3: "Figma",
        age: 30,
        yearExperience: "2 years",
        contactNo: "656 996 95984",
        emailAd: "example@email.com",
        workExperience: [
            {
                comp: "Rosenbaum Group",
                position: "Java Software Engineer",
                tenure: "Jan 2019 - Dec 2020",
            },
            {
                comp: "Crona, Durgan and Schneider",
                position: "Network Engineer",
                tenure: "Feb 2018 - Oct 2019",
            },
        ],
        valuableSkill: ["Sketch", "Figma", "ReactJS", "VueJS", "PHP", "Laravel"],

    },
    {
        id: 2,
        devImg: "https://snipboard.io/OfYjn3.jpg",
        devName: "Homer B. Grew",
        devLocation: "ROOM 106 Cch Building Alfaro Street Salcedo Village 1200, Makati City, Metro Manila",
        devMainRole: "Mobile",
        skillSet: "Full Time",
        skillSet2: "Illustrator",
        skillSet3: "Design",
        age: 28,
        yearExperience: "3 years",
        contactNo: "632 957 5454",
        emailAd: "AlfredATalley@rhyta.com",
        workExperience: [
            {
                comp: "Turcotte PLC",
                position: "Full Stack Developer - Sydney",
                tenure: "Mar 2015 - Jan 2018",
            },
            {
                comp: "Satterfield Inc",
                position: "Python Developer",
                tenure: "Nov 2012 - Dec 2014",
            },
        ], 
        valuableSkill: ["Illustrator", "Design", "Flutter", "ReactJS", "Hive"],
    },
    {
        id: 3,
        devImg: "https://snipboard.io/xCH2Nu.jpg",
        devName: " Meghan Schmitt",
        devLocation: "Ncrpasig City2705 Jollibee Plaza, Emerald Ave., Ortigas Center NCR, Pasig City, Metro Manila",
        devMainRole: "Visual Designers",
        skillSet: "Part Time",
        skillSet2: "Effects",
        skillSet3: "HTML",
        age: 26,
        yearExperience: "3 years",
        contactNo: "632 957 5454",
        emailAd: "westley.witting@jacobs.com",
        workExperience: [
            {
                comp: "Mosciski, Spinka and Bernhard",
                position: "Service Designer",
                tenure: "Dec 2017 - Dec 2020",
            },
            {
                comp: "Ferry-Ondricka",
                position: "Digital Workplace Solution Designer",
                tenure: "Jan 2012 - Nov 2016",
            },
        ],
        valuableSkill: ["Effects", "HTML", "CSS", "Sass", "Javascript"],
    },
    {
        id: 4,
        devImg: "https://snipboard.io/z4wpXq.jpg",
        devName: "Hanna Bartoletti ",
        devLocation: "8 Dioquino St. Corner 16th Ave., Cubao 1110, Quezon City, Metro Manila",
        devMainRole: "DevOps",
        skillSet: "Full Time",
        skillSet2: "Responsive",
        skillSet3: "Mobile",
        age: 35,
        yearExperience: "7 years",
        contactNo: "22-5014010",
        emailAd: "meghan.kuvalis@kreiger.com",
        workExperience: [
            {
                comp: "Glover-Hermann",
                position: "Cloud DevOps SRE Engineer",
                tenure: "Nov 2002 - Dec 2010",
            },
            {
                comp: "Windler Ltd",
                position: "Project Manager",
                tenure: "Jan 2012 - Sep 2016",
            },
        ],
        valuableSkill: ["Responsive", "Mobile", "ReactJS", "Dart"],
    },
    {
        id: 5,
        devImg: "https://snipboard.io/9iRC4L.jpg",
        devName: "Arn Ubowski",
        devLocation: "54 Tirad Pass Street, Morning Breeze Subdivision, Caloocan City, Metro Manila",
        devMainRole: "Data Scientists",
        skillSet: "Full Time",
        skillSet2: "UX",
        skillSet3: "UI",
        age: 32,
        yearExperience: "8 years",
        contactNo: "45-4238934",
        emailAd: "gage21@zboncak.com",
        workExperience: [
            {
                comp: "Will-McKenzie",
                position: "Program Test Lead",
                tenure: "Apr 2010 - Mar 2015",
            },
            {
                comp: "Glover and Sons",
                position: "Java Software Engineer",
                tenure: "Jun 2017 - Dec 2020",
            },
        ],
        valuableSkill: ["UX", "UI", "Python"],
    },
    {
        id: 6,
        devImg: "https://snipboard.io/VXF9pr.jpg",
        devName: "Sarah Towne",
        devLocation: "736 Emerald St. Posadas Village Sucat, NCR, Muntinlupa City, Metro Manila",
        devMainRole: "Web",
        skillSet: "Part Time",
        skillSet2: "Java",
        skillSet3: "C++",
        age: 33,
        yearExperience: "5 years",
        contactNo: "81-7822895",
        emailAd: "novella68@metz.com",
        workExperience: [
            {
                comp: "Watsica-Kirlin",
                position: "Digital Workplace Solution Designer",
                tenure: "Feb 2015 - Mar 2016",
            },
            {
                comp: "Yost, Hand and Abernathy",
                position: "Service Designer",
                tenure: "Jul 2017 - Dec 2020",
            },
            {
                comp: "Sanford, Mayert and Hegmann",
                position: "Data Centre Infrastructure Analyst",
                tenure: "Jan 2019 - Dec 2020",
            },
        ],
        valuableSkill: ["Java", "C++", "Python"],
    },
    {
        id: 7,
        devImg: "https://snipboard.io/BNVAUI.jpg",
        devName: "Mariane Miller ",
        devLocation: "1629 G Araneta Avenue Corner Sgt. Rivera, Quezon City, Quezon City",
        devMainRole: "Digital Project",
        skillSet: "Part Time",
        skillSet2: "UX Writing",
        skillSet3: "Figma",
        age: 24,
        yearExperience: "4 years",
        contactNo: "72-4634718",
        emailAd: "mkrajcik@gorczany.org",
        workExperience: [
            {
                comp: "Zboncak-Gleason",
                position: "Network Engineer",
                tenure: "Jan 2019 - Dec 2020",
            },
            {
                comp: "Sanford, Mayert and Hegmann",
                position: "IAM SailPoint DevOps Engineer",
                tenure: "Jan 2018 - Dec 2019",
            },
        ],
        valuableSkill: ["UX Writing", "Figma", "Javascript", "MySQL", "Hive"],
    },
    {
        id: 8,
        devImg: "https://snipboard.io/A1b3Mr.jpg",
        devName: "Eileen Weimann",
        devLocation: "1216 Acacia Avenue, Madrigal Business Park, Ayala Alabang 1770, Muntinlupa City, Metro Manila",
        devMainRole: "Branding",
        skillSet: "Full Time",
        skillSet2: "Animations",
        skillSet3: "Sketch",
        age: 28,
        yearExperience: "5 years",
        contactNo: "72-1346924",
        emailAd: "gerson98@considine.com",
        workExperience: [
            {
                comp: "Turcotte, Pfannerstill and Nader",
                position: "Market Data Engineer",
                tenure: "Jan 2019 - Dec 2020",
            },
            {
                comp: "Considine, Jerde and Schumm",
                position: "Cloud DevOps SRE Engineer",
                tenure: "Jan 2019 - Dec 2020",
            },
        ],
        valuableSkill: ["Animations", "Sketch", "Javascript", "MySQL", "SQLite"],
    },
    {
        id: 9,
        devImg: "https://snipboard.io/hKMaxQ.jpg",
        devName: "Fabian Pagac",
        devLocation: "Door 2 Lua Building, McArthur Highway, Matina, Davao City, Davao del Sur",
        devMainRole: "Visual Designers",
        skillSet: "Freelance",
        skillSet2: "IOS",
        skillSet3: "Responsive",
        age: 21,
        yearExperience: "1 year",
        contactNo: "95-6020341",
        emailAd: "alice95@johnson.com",
        workExperience: [
            {
                comp: "Breitenberg, Mills and Hudson",
                position: "Program Test Lead",
                tenure: "Jan 2019 - Dec 2020",
            },
        ],
        valuableSkill: ["IOS", "Responsive", "Kotlin", "Swift", "Dart"],
    },
    {
        id: 10,
        devImg: "https://snipboard.io/YCB9VU.jpg",
        devName: "Colt Kautzer",
        devLocation: "5/F Ortigas Ortigas Avenue 1600, Pasig City, Pasig City",
        devMainRole: "Mobile",
        skillSet: "Full Time",
        skillSet2: "UX",
        skillSet3: "UI",
        age: 25,
        yearExperience: "5 years",
        contactNo: "95-6020341",
        emailAd: "alice95@johnson.com",
        workExperience: [
            {
                comp: "Considine, Jerde and Schumm",
                position: "Tech Resilience Data Analyst",
                tenure: "Jan 2019 - Dec 2020",
            },
            {
                comp: "Breitenberg, Mills and Hudson",
                position: "Manager- Test Manager",
                tenure: "Oct 2017 - Dec 2019",
            },
        ],
        valuableSkill: ["UX", "UI", "Kotlin", "Swift", "Java"],
    },
    {
        id: 11,
        devImg: "https://snipboard.io/PgjWZU.jpg",
        devName: "Milford King",
        devLocation: "64 Judge Juan Luna Street, Barangay Bungad, SFDM, Quezon City, Metro Manila",
        devMainRole: "Data Scientists",
        skillSet: "Part Time",
        skillSet2: "Javscript",
        skillSet3: "HTML",
        age: 27,
        yearExperience: "2 years",
        contactNo: "24-8117609",
        emailAd: "ydurgan@bartell.com",
        workExperience: [
            {
                comp: "Reinvent Out-Of-The-Box Models",
                position: "DevOps Cloud Engineer",
                tenure: "Jan 2019 - Dec 2020",
            },
            {
                comp: "	Schiller, Johns and Moen",
                position: "Data Business Analyst",
                tenure: "Jan 2019 - Dec 2020",
            },
        ],
        valuableSkill: ["Javscript", "HTML", "CSS", "Sass"],
    },
    {
        id: 12,
        devImg: "https://snipboard.io/0g5UTA.jpg",
        devName: "Deon Kunde III",
        devLocation: "MC Home Depot, 168 Ortigas Avenue Corner A. Rodriguez Avenue, Pasig City, Metro Manila",
        devMainRole: "UI/UX Designer",
        skillSet: "Full Time",
        skillSet2: "Sketch",
        skillSet3: "Layout",
        age: 24,
        yearExperience: "3 years",
        contactNo: "90-4019106",
        emailAd: "ikrajcik@rosenbaum.net",
        workExperience: [
            {
                comp: "Streamline Customized Partnerships",
                position: "Python Developer",
                tenure: "Jan 2019 - Dec 2020",
            },
            {
                comp: "Effertz Inc",
                position: "Developer - Settlement Technology",
                tenure: "Jan 2019 - Dec 2020",
            },
        ],
        valuableSkill: ["Sketch", "Layout", "UI", "UX"],
    },
    {
        id: 13,
        devImg: "https://snipboard.io/Bq49YI.jpg",
        devName: "Jackie Shields",
        devLocation: "174-C N Carpio Street 6th Avenue 1400, Caloocan City, Caloocan City",
        devMainRole: "Software Developers",
        skillSet: "Full Time",
        skillSet2: "ReactJS",
        skillSet3: "Python",
        age: 25,
        yearExperience: "3 years",
        contactNo: "30-6968639",
        emailAd: "xblanda@fadel.biz",
        workExperience: [
            {
                comp: "Envisioneer Distributed Roi",
                position: "Data Centre Infrastructure Analyst",
                tenure: "Jan 2019 - Dec 2020",
            },
            {
                comp: "Mosciski, Spinka and Bernhard",
                position: "IAM SailPoint DevOps Engineer",
                tenure: "Jan 2019 - Dec 2020",
            },
        ],
        valuableSkill: ["ReactJS", "Python", "PHP", "Laravel"],
    },
    {
        id: 14,
        devImg: "https://snipboard.io/RAjJs3.jpg",
        devName: "Mandy Cruz",
        devLocation: "108 Herrera St., Legaspi Village, NCR, Makati City, Metro Manila",
        devMainRole: "Python Developer",
        skillSet: "Full Time",
        skillSet2: "Sketch",
        skillSet3: "Figma",
        age: 22,
        yearExperience: "2 years",
        contactNo: "68-6906396",
        emailAd: "udibbert@hand.biz",
        workExperience: [
            {
                comp: "Architect Innovative Mindshare",
                position: "Cloud DevOps SRE Engineer",
                tenure: "Jan 2019 - Dec 2020",
            },
            {
                comp: "Yost, Hand and Abernathy	",
                position: "Senior Network Security Engineer",
                tenure: "Jan 2019 - Dec 2020",
            },
        ],
        valuableSkill: ["Sketch", "Figma", "PHP", "Laravel"],
    },
    {
        id: 15,
        devImg: "https://snipboard.io/kAirOv.jpg",
        devName: "Twila Wisoky",
        devLocation: "2/F Marisan Arcade2943 Marconi StreetSouth Superhighway 4200, Makati City, Metro Manila",
        devMainRole: "Java Developer",
        skillSet: "Illustrator",
        skillSet2: "Design",
        skillSet3: "Figma",
        age: 32,
        yearExperience: "6 years",
        contactNo: "72-4634718",
        emailAd: "mkrajcik@gorczany.org",
        workExperience: [
            {
                comp: "Cultivate Open-Source Supply-Chains",
                position: "Executive Financial System Operations (RPA- BluePrism)",
                tenure: "Jan 2019 - Dec 2020",
            },
            {
                comp: "Turcotte, Pfannerstill and Nader",
                position: "Manager- Test Manager",
                tenure: "Jan 2019 - Dec 2020",
            },
        ],
        valuableSkill: ["Design", "Figma", "HTML", "CSS", "C#"],
    }, {
        id: 16,
        devImg: "https://snipboard.io/tJSh5P.jpg",
        devName: "Favian Dietrich",
        devLocation: "Quiriono Avenue corner M. Rodriguez Street, La Huerta, Paranaque City, Metro Manila",
        devMainRole: "JavaScript Developer",
        skillSet: "Full Time",
        skillSet2: "Sketch",
        skillSet3: "Figma",
        age: 30,
        yearExperience: "6 years",
        contactNo: "90-4019106",
        emailAd: "ikrajcik@rosenbaum.net",
        workExperience: [
            {
                comp: "Innovate Robust E-Tailers",
                position: "Digital Workplace Solution Designer",
                tenure: "Jan 2019 - Dec 2020",
            },
            {
                comp: "Lakin-Daugherty",
                position: "Service Designer",
                tenure: "Jan 2010 - Jan 2012",
            },
        ],
        valuableSkill: ["Sketch", "Figma", "HTML", "CSS", "C#"],
    },
   
];

export default DeveloperList