

const JobList = [
    {
        id: 1,
        company: "Breitenberg-Stamm",
        address: "Fuente Osmena, Cebu City, Cebu,",
        compDescription: "Networked Tangible Algorithm",
        tagline: "Harness 24/365 Deliverables",
        companyEmail: "weimann.una@aufderhar.com",
        ein: "60-6484991",  
        jobTitle: "Full Stack",
        jobDescription: ["Conduct research and deconstruct our users digital interactions and habits.",
        "Come up with UI and UX strategies based on our target goals.",
        "Create and maintain digital assets, such as interface design files, design and prototyping tools: e.g., Sketch and InVision.",
        "Design, build, and maintain highly reusable JavaScript, HTML and CSS code",
    ],
        skills: ["3+ years experience as a front-end developer.",
        "2+ years experience as a UI/UX designer.",
        "A portfolio that demonstrates both JavaScript proficiency and understanding of SOLID design principles (plugins, node packages, etc.).",
        "Expert knowledge of CSS, CSS extension languages (Less, Sass), and CSS preprocessor tools.",
        "Expert knowledge of HTML5 and its best practices.",
    ],
        category: "Web Application",
        jobSnippet: "We are looking for a highly skilled computer programmer who is comfortable with both front and back end programming.",
        employmentStatus: "Full-Time",
        salary: 25000,
        aor: "Office Base",
    
    },
    {
        id: 2,
        company: "Harber-Kreiger",
        address: "36 ADB Ledesma, Jaro, Iloilo City, Iloilo,",
        compDescription: "Profit-Focused Hybrid Intranet",
        tagline: "Evolve Dynamic Technologies",
        companyEmail: "vkihn@leuschke.com",
        ein: "92-4563185",
        jobTitle: "Desktop Application",
        jobDescription: [
            "Developing software solutions to meet customer needs.",
            "Creating and implementing the source code of new applications.",
            "Testing source code and debugging code.",
            "Evaluating existing applications and performing updates and modifications.",
            "Developing technical handbooks to represent the design and code of new applications.",
        ],
        skills: [ 
            "A bachelor's degree in computer science or related field." ,
            "A working knowledge of programming languages such as Java and ORACLE.",
            "Experience in application and software development." ,
            "Knowledge of software design and programming principles.",
            "Good mathematical and problem-solving skills.",
        ],
        category: "Desktop Application",
        jobSnippet: "We are looking for Junior Software Developers to join our team! We are a blockchain based start-up delivering solutions for the Cardano blockchain network.",
        employmentStatus: "Part-time",
        salary: 27000,
        aor: "Work From Home",
    },
    {
        id: 3,
        company: "Turcotte PLC",
        address: "Davao Recto Business Cente, Davao City, Davao del Sur",
        compDescription: "Profound Encompassing Matrices",
        tagline: "Synergize Impactful Bandwidth",
        companyEmail: "weissnat.annetta@willms.com",
        ein: "47-8280284",
        jobTitle: "React Native Developer",
        jobDescription: [
            "Support the entire application lifecycle (concept, design, test, release and support)" ,
            "Produce fully functional mobile applications writing clean code" ,
            "Gather specific requirements and suggest solution" ,
            "Write unit and UI tests to identify malfunctions",
            "Troubleshoot and debug to optimize performance",
            ],
        skills: [
            "Proven work experience as a Mobile developer",
            "In-depth knowledge of at least one programming language like Swift and Java",
            "Experience with third-party libraries and APIs",
            "Familiarity with OOP design principles",
            "Excellent analytical skills with a good problem-solving attitude",
            "Ability to perform in a team environment",
            ],
        category: "Mobile Development",
        jobSnippet: "We are looking for someone who can maintain our Mobile app development needs and be involved in solving blockchain based problems.",
        employmentStatus: "Full-time",
        salary: 29000,
        aor: "Office Base",
    },
    {
        id: 4,
        company: "Mosciski, Langworth and Medhurst",
        address: "5665 Sta. Monica Street, Don Galo, Paranaque City, Metro Manila",
        compDescription: "Diverse Content-Based Function",
        tagline: "Innovate Wireless Infomediaries",
        companyEmail: "berniece26@mraz.com",
        ein: "86-6311452",
        jobTitle: "Flutter App Developer",
        jobDescription: ["Java/Swift experience",
            "Understanding of Android Keyboard API",
            "Experience with optimizing applications for Material Design"
        ],
        skills: ["Have two or more iOS/Android apps developed with Flutter.",
            "5+ years in mobile software development",
            "Over one year developing Flutter applications for mobile",
            "Experience with third-party libraries and APIs",
            "Understanding of the Agile development life-cycle",
            "Experience with automated testing and building",

        ],
        category: "Mobile Development",
        jobSnippet: "We are looking to train Junior Software Developers with at least 3 months to 1 year experience.",
        employmentStatus: "Part-time",
        salary: 25000,
        aor: "Office Base",
    },
    {
        id: 5,
        company: "Lind-Boehm",
        address: "399-B Shaw Boulevard Corner Samat Street 1500, Mandaluyong City",
        compDescription: "User-Friendly Global Forecast",
        tagline: "Utilize Distributed Solutions",
        companyEmail: "cummerata.elisa@brown.biz",
        ein: "16-3977536",
        jobTitle: "Front-End/ UI-UX",
        jobDescription: ["Conduct research and deconstruct our users digital interactions and habits.",
            "Come up with UI and UX strategies based on our target goals.",
            "Create and maintain digital assets, such as interface design files, Sketch and InVision.",
            "Design, build, and maintain highly reusable JavaScript, HTML and CSS code",

        ],
        skills: ["3+ years experience as a front-end developer.",
            "2+ years experience as a UI/UX designer.",
            "A portfolio that demonstrates both JavaScript proficiency and understanding of SOLID design principles (plugins, node packages, etc.).",
            "Expert knowledge of CSS, CSS extension languages (Less, Sass), and CSS preprocessor tools.",
            "Expert knowledge of HTML5 and its best practices.",
            "Proficiency in designing interfaces and building clickable prototypes using Sketch, InVision, Axure, etc.",
        ],
        category: "Web Application",
        jobSnippet: "Front end developers are responsible for ensuring the alignment of web design and user experience and requirements, optimizing web pages for performance.",
        employmentStatus: "Full-time",
        salary: 25000,
        aor: "Work From Home",
    },
    {
        id: 6,
        company: "Hartmann, Hilpert and Bernier",
        address: "1227 V Zamora 1200, Makati City, Metro Manila",
        compDescription: "Open-Architected Contextually-Based Approach",
        tagline: "Revolutionize Cross-Platform Deliverables",
        companyEmail: "gorczany.malvina@welch.com",
        ein: "37-2855778",
        jobTitle: "Back-End Developer",
        jobDescription: ["Compile and analyze data, processes, and codes to troubleshoot problems and identify areas for improvement.",
            "Collaborating with the front-end developers and other team members to establish objectives and design more functional.",
            "Developing ideas for new programs, products, or features by monitoring industry developments and trends.",
            "Recording data and reporting it to proper parties, such as clients or leadership.",
            "Participating in continuing education and best practices,and better assist other team members.",
        ],
        skills: ["Bachelors degree in computer programming, computer science, or a related field.",
            "More education or experience may be required.",
            "Fluency or understanding of specific languages, such as Java, PHP, or Python, and operating systems may be required.",
            "Strong understanding of the web development cycle and programming techniques and tools.",
            "Focus on efficiency, user experience, and process improvement.",
            "Excellent project and time management skills.",
            "Strong problem solving and verbal and written communication skills.",
        ],
        category: "Web Application",
        jobSnippet: "As the premier digital partner with offices in Auckland, Sydney, and Manila, they have been solving challenging problems and delivering award-winning, best-of-breed eCommerce solutions for over a decade.",
        employmentStatus: "Part-time",
        salary: 35000,
        aor: "Work From Home",
    },
    {
        id: 7,
        company: "Prohaska and Sons",
        address: "2039 Lords Way, Bolivar, Tennessee(TN), 38008",
        compDescription: "Reduced Transitional Core",
        tagline: "Envisioneer Dot-Com Partnerships",
        companyEmail: "hammes.jaylan@haley.com",
        ein: "36-4670129",
        jobTitle: "POS Application",
        jobDescription: ["Supports POS software, hardware development cycle to include needs analysis, testing, troubleshooting and deployment",
            "Analyzes users needs and develops functional specifications",
            "Designs and codes programs and scripts to administer the POS systems",
            "Performs functional testing, interpretation and analysis of results of tests",
            "Deploys software and hardware",
            "Provides technical support for POS Help Desk",
            "Trains users and technical staff in the use of new software",
        ],
        skills: ["C# programming experience required. .NET 3.0+, MSSQL, WPF, WCF, Entity Framework",
            "Four year degree in computer science or four years related work experience",
            "Knowledge of PCs and telecommunications required",
            "Knowledge in setup, configuration and troubleshooting of LAN/WAN networks",
            "Ability to work occasional weekends and evenings for special projects",
            "Some C# or VB.NET for desktop applications experience a plus"
        ],
        category: "Desktop Application",
        jobSnippet: "This is an entry level role, expected to contribute under supervision of more senior team members to the development (or maintenance) of applications",
        employmentStatus: "Full-time",
        salary: 40000,
        aor: "Office Base",
    },
    {
        id: 8,
        company: "Connelly, Thompson and Pfeffer",
        address: "1483 Alexander Avenue, Bethel Island, California(CA), 94511",
        compDescription: "Object-Based 3Rdgeneration Database",
        tagline: "Deploy Virtual Supply-Chains",
        companyEmail: "mabel78@howe.com",
        ein: "95-3508659",
        jobTitle: "3D Games Developer",
        jobDescription: ["Implement game functionality as per communicated design",
            "Translate design specification into functional game",
            "Communicate with other team members to establish effective pipeline and integrate media assets",
            "Design, build, and maintain efficient, reusable, and reliable code",
            "Ensure the best possible performance, quality, and responsiveness of applications",
            "Identify bottlenecks and bugs, and devise solutions to address and mitigate these problems"
        ],
        skills: ["Excellent knowledge of Unity, including experience with scripting GUI styles, and user session management",
            "Familiarity with level design and planning",
            "Experience with game physics and particle systems",
            "Experience with mobile and console game development",
            "Experience optimizing memory and space usage for support of older hardware",
            "Experience with 3D is a plus",
            "Prior experience with a well-known mobile title or AAA titles are a significant asset",
        ],
        category: "Desktop Application",
        jobSnippet: "My name is Soo from Kreloses and were looking for 3 friendly junior developers (graduates are welcome) to join our product team.",
        employmentStatus: "Full-time",
        salary: 29000,
        aor: "Office Base",
    },
    {
        id: 9,
        company: "Haley-Stiedemann",
        address: "2523 White Pine Lane, Culpeper, Virginia(VA), 22701",
        compDescription: "Versatile Holistic Adapter",
        tagline: "Brand Virtual Bandwidth",
        companyEmail: "bailee.murray@stamm.com",
        ein: "68-9751255",
        jobTitle: "C#, C++",
        jobDescription: ["Supports POS software, hardware development cycle to testing, troubleshooting and deployment",
            "Analyzes users needs and develops functional specifications",
            "Designs and codes programs and scripts to administer the POS systems, install software updates and perform other POS functions",
            "Performs functional testing, interpretation and analysis of results of tests",
            "Deploys software and hardware",
            "Provides technical support for POS Help Desk",
            "Trains users and technical staff in the use of new software",
            "Supports user maintenance requests"
        ],
        skills: ["C# programming experience required. .NET 3.0+, MSSQL, WPF, WCF, Entity Framework",
            "Four year degree in computer science or four years related work experience",
            "Knowledge of PCs and telecommunications required",
            "Knowledge in setup, configuration and troubleshooting of LAN/WAN networks",
            "Ability to work occasional weekends and evenings for special projects",
            "Some C# or VB.NET for desktop applications experience a plus"
        ],
        category: "Desktop Application",
        jobSnippet: "For this role, you will be working on a complex web application written in C# on the back end and typescript/react on the front end",
        employmentStatus: "Full-time",
        salary: 30000,
        aor: "Work From Home",
    },
    {
        id: 10,
        company: "Boyle Ltd",
        address: "2474 Hershell Hollow Road, Everett, Washington(WA), 98208",
        compDescription: "Multi-Channelled Full-Range Functionalities",
        tagline: "Target Proactive Users",
        companyEmail: "kcorwin@kassulke.org",
        ein: "71-3045624",
        jobTitle: "Full Stack Web Developer",
        jobDescription: ["Conduct research and deconstruct our users digital interactions and habits.",
        "Come up with UI and UX strategies based on our target goals.",
        "Create and maintain digital assets, such as interface design files, and prototyping tools: e.g., Sketch and InVision.",
        "Design, build, and maintain highly reusable JavaScript, HTML and CSS code",
        "Understand the limitations of our tech stack and business model and provide technical advice wherever necessary.",
    ],
        skills: ["3+ years experience as a front-end developer.",
        "2+ years experience as a UI/UX designer.",
        "A portfolio that demonstrates both JavaScript SOLID design principles (plugins, node packages, etc.).",
        "Expert knowledge of CSS, CSS extension languages (Less, Sass), and CSS preprocessor tools.",
        "Expert knowledge of HTML5 and its best practices.",
    ],
        category: "Web Application",
        jobSnippet: "Were offering a unique home-based opportunity for a passionate, enthusiastic Junior Developer to join a London-based software development company",
        employmentStatus: "Full-time",
        salary: 55000,
        aor: "Office Base",
    },
    {
        id: 11,
        company: "Boyle Ltd",
        address: "2474 Hershell Hollow Road, Everett, Washington(WA), 98208",
        compDescription: "Multi-Channelled Full-Range Functionalities",
        tagline: "Target Proactive Users",
        companyEmail: "kcorwin@kassulke.org",
        ein: "71-3045624",
        jobTitle: "Back-End Developer",
        jobDescription: ["Compile and analyze data, processes, and codes to troubleshoot problems and identify areas for improvement.",
            "Collaborating with the front-end developers and other team members to establish  cohesive codes to enhance the user experience.",
            "Developing ideas for new programs, products, or features by monitoring industry developments and trends.",
            "Recording data and reporting it to proper parties, such as clients or leadership.",
            "Taking lead on projects, as needed."
        ],
        skills: ["Bachelors degree in computer programming, computer science, or a related field.",
            "More education or experience may be required.",
            "Strong understanding of the web development cycle and programming techniques and tools.",
            "Focus on efficiency, user experience, and process improvement.",
            "Excellent project and time management skills.",
            "Strong problem solving and verbal and written communication skills.",
        ],
        category: "Web Application",
        jobSnippet: "Were looking for talent and passion for tech; the technologies you have experience with are less important",
        employmentStatus: "Full-time",
        salary: 55000,
        aor: "Work From Home",
    },
    {
        id: 12,
        company: "Hill Inc",
        address: "353 Fidler Drive, San Antonio, Texas(TX), 78201",
        compDescription: "Reverse-Engineered Interactive Frame",
        tagline: "Grow Distributed Convergence",
        companyEmail: "qkoelpin@murray.com",
        ein: "61-8010790", 
        jobTitle: "POS Application",
        jobDescription: ["Supports POS software, hardware development cycle to include testing, troubleshooting and deployment",
            "Analyzes users needs and develops functional specifications",
            "Designs and codes programs and scripts to administer the POS systems, install software updates and perform other POS functions",
            "Performs functional testing, interpretation and analysis of results of tests",
            "Deploys software and hardware",
            "Provides technical support for POS Help Desk",
            "Trains users and technical staff in the use of new software",
        ],
        skills: ["C# programming experience required. .NET 3.0+, MSSQL, WPF, WCF, Entity Framework",
            "Four year degree in computer science or four years related work experience",
            "Knowledge of PCs and telecommunications required",
            "Knowledge in setup, configuration and troubleshooting of LAN/WAN networks",
            "Ability to work occasional weekends and evenings for special projects",
            "Some C# or VB.NET for desktop applications experience a plus"
        ],
        category: "Desktop Application",
        jobSnippet: "Position requires working with a small team to develop custom web and mobile applications for an offshore company.",
        employmentStatus: "Part-time",
        salary: 28000,
        aor: "Office Base",
    },
    {
        id: 13,
        company: "Zemlak Ltd",
        address: "3027 Bridge Street, Tulsa, Oklahoma(OK), 74120",
        compDescription: "Ergonomic Assymetric Model",
        tagline: "Reinvent Synergistic E-Business",
        companyEmail: "devonte.parisian@buckridge.info",
        ein: "01-5811824", 
        jobTitle: "3D Games Developer",
        jobDescription: ["Implement game functionality as per communicated design",
            "Translate design specification into functional game",
            "Communicate with other team members to establish effective pipeline and integrate media assets",
            "Design, build, and maintain efficient, reusable, and reliable code",
            "Ensure the best possible performance, quality, and responsiveness of applications",
            "Identify bottlenecks and bugs, and devise solutions to address and mitigate these problems"
        ],
        skills: ["Excellent knowledge of Unity, including experience with scripting, styles, and user session management",
            "Familiarity with level design and planning",
            "Experience with game physics and particle systems",
            "Experience with mobile and console game development",
            "Experience optimizing memory and space usage for support of older hardware",
            "Experience with 3D is a plus",
        ],
        category: "Desktop Application",
        jobSnippet: "Zemlak Ltd is an all-Filipino owned Fintech company in the Philippines that provides end-to-end digital banking solutions.",
        employmentStatus: "Part-time",
        salary: 25000,
        aor: "Office Base",
    },
    {
        id: 14,
        company: "Rosenbaum-Rath",
        address: "4559 Hide A Way Road, San Jose, California(CA), 95113",
        compDescription: "Automated Disintermediate Graphicinterface",
        tagline: "Aggregate Ubiquitous Niches",
        companyEmail: "satterfield.golda@powlowski.com",
        ein: "67-4484195",
        jobTitle: "C#, C++",
        jobDescription: ["Supports POS software, hardware development specifications, testing, troubleshooting and deployment",
            "Analyzes users needs and develops functional specifications",
            "Designs and codes programs and scripts to administer the POS systems, install software updates and perform other POS functions",
            "Performs functional testing, interpretation and analysis of results of tests",
            "Deploys software and hardware",
            "Provides technical support for POS Help Desk",
        ],
        skills: ["C# programming experience required. .NET 3.0+, MSSQL, WPF, WCF, Entity Framework",
            "Four year degree in computer science or four years related work experience",
            "Knowledge of PCs and telecommunications required",
            "Knowledge in setup, configuration and troubleshooting of LAN/WAN networks",
            "Ability to work occasional weekends and evenings for special projects",
            "Some C# or VB.NET for desktop applications experience a plus"
        ],
        category: "Desktop Application",
        jobSnippet: "As a Software Engineer, you will be a core contributor to our AI data solutions platform.",
        employmentStatus: "Part-time",
        salary: 25000,
        aor: "Office Base",
    },
    {
        id: 15,
        company: "Breitenberg-Stamm",
        address: "1816 Bingamon Road, Willoughby, Ohio(OH), 44094",
        compDescription: "Networked Tangible Algorithm",
        tagline: "Harness 24/365 Deliverables",
        companyEmail: "weimann.una@aufderhar.com",
        ein: "60-6484991",  
        jobTitle: "Full Stack",
        jobDescription: ["Conduct research and deconstruct our users digital interactions and habits.",
        "Come up with UI and UX strategies based on our target goals.",
        "Create and maintain digital assets, such as interface design files, wireframes,typing tools: e.g., Sketch and InVision.",
        "Design, build, and maintain highly reusable JavaScript, HTML and CSS code",
        "Understand the limitations of our tech stack and business model and provide technical advice wherever necessary.",
    ],
        skills: ["3+ years experience as a front-end developer.",
        "2+ years experience as a UI/UX designer.",
        "A portfolio that demonstrates both JavaScript proficiency and understanding of SOLID design principles (plugins, node packages, etc.).",
        "Expert knowledge of CSS, CSS extension languages (Less, Sass), and CSS preprocessor tools.",
        "Expert knowledge of HTML5 and its best practices.",
        "Proficiency in designing interfaces and building clickable prototypes using Sketch, InVision, Axure, etc.",
        "A history of deconstructing user behavior to create an improvedn the form of blog posts, articles, screencasts, etc.",
    ],
        category: "Web Application",
        jobSnippet: "You should be someone who is passionate about implementing rich, highly functional, and highly performant user interfaces that spark delight",
        employmentStatus: "Full-Time",
        salary: 0,
        aor: "Office Base",
    },
    {
        id: 16,
        company: "Hill Inc",
        address: "353 Fidler Drive, San Antonio, Texas(TX), 78201",
        compDescription: "Reverse-Engineered Interactive Frame",
        tagline: "Grow Distributed Convergence",
        companyEmail: "qkoelpin@murray.com",
        ein: "61-8010790", 
        jobTitle: "POS Application",
        jobDescription: ["Supports POS software, hardware development cycle specifications, testing, troubleshooting and deployment",
            "Analyzes users needs and develops functional specifications",
            "Designs and codes programs and scripts to administer the POS systems, install software updates and perform other POS functions",
            "Performs functional testing, interpretation and analysis of results of tests",
            "Deploys software and hardware",
            "Provides technical support for POS Help Desk",
        ],
        skills: ["C# programming experience required. .NET 3.0+, MSSQL, WPF, WCF, Entity Framework",
            "Four year degree in computer science or four years related work experience",
            "Knowledge of PCs and telecommunications required",
            "Knowledge in setup, configuration and troubleshooting of LAN/WAN networks",
            "Ability to work occasional weekends and evenings for special projects",
            "Some C# or VB.NET for desktop applications experience a plus"
        ],
        category: "Desktop Application",
        jobSnippet: "Position requires working with a small team to develop custom web and mobile applications for an offshore company.",
        employmentStatus: "Part-time",
        salary: 28000,
        aor: "Office Base",
    },

    {
        id: 17,
        company: "Breitenberg-Stamm",
        address: "Fuente Osmena, Cebu City, Cebu,",
        compDescription: "Networked Tangible Algorithm",
        tagline: "Harness 24/365 Deliverables",
        companyEmail: "weimann.una@aufderhar.com",
        ein: "60-6484991",  
        jobTitle: "Full Stack",
        jobDescription: ["Conduct research and deconstruct our users digital interactions and habits.",
        "Come up with UI and UX strategies based on our target goals.",
        "Create and maintain digital assets, such as interface design files, wireframes, e.g., Sketch and InVision.",
        "Design, build, and maintain highly reusable JavaScript, HTML and CSS code",
        "Understand the limitations of our tech stack and business model and provide technical advice wherever necessary.",
    ],
        skills: ["3+ years experience as a front-end developer.",
        "2+ years experience as a UI/UX designer.",
        "A portfolio that demonstrates both JavaScript sign principles (plugins, node packages, etc.).",
        "Expert knowledge of CSS, CSS extension languages (Less, Sass), and CSS preprocessor tools.",
        "Expert knowledge of HTML5 and its best practices.",
        "Proficiency in designing interfaces and building clickable prototypes using Sketch, InVision, Axure, etc.",

    ],
        category: "Web Application",
        jobSnippet: "We are looking for a highly skilled computer programmer who is comfortable with both front and back end programming.",
        employmentStatus: "Full-Time",
        salary: 25000,
        aor: "Office Base",
    
    },
    {
        id: 18,
        company: "Lind-Boehm",
        address: "399-B Shaw Boulevard Corner Samat Street 1500, Mandaluyong City",
        compDescription: "User-Friendly Global Forecast",
        tagline: "Utilize Distributed Solutions",
        companyEmail: "cummerata.elisa@brown.biz",
        ein: "16-3977536",
        jobTitle: "Front-End/ UI-UX",
        jobDescription: ["Conduct research and deconstruct our users digital interactions and habits.",
            "Come up with UI and UX strategies based on our target goals.",
            "Create and maintain digital assets, such as interface design files,ototyping tools: e.g., Sketch and InVision.",
            "Design, build, and maintain highly reusable JavaScript, HTML and CSS code",
            "Understand the limitations of our tech stack and business model and provide technical advice wherever necessary.",
        ],
        skills: ["3+ years experience as a front-end developer.",
            "2+ years experience as a UI/UX designer.",
            "A portfolio that demonstrates both JavaScript proficiency design principles (plugins, node packages, etc.).",
            "Expert knowledge of CSS, CSS extension languages (Less, Sass), and CSS preprocessor tools.",
            "Expert knowledge of HTML5 and its best practices.",
            "Proficiency in designing interfaces and building clickable prototypes using Sketch, InVision, Axure, etc.",
            "A history of deconstructing user behavior to create an improved experience for users, articles, screencasts, etc.",
        ],
        category: "Web Application",
        jobSnippet: "Front end developers are responsible for ensuring the alignment of web design and user experience and requirements, optimizing web pages for performance.",
        employmentStatus: "Full-time",
        salary: 25000,
        aor: "Work From Home",
    },
    {
        id: 19,
        company: "Turcotte PLC",
        address: "Davao Recto Business Cente, Davao City, Davao del Sur",
        compDescription: "Profound Encompassing Matrices",
        tagline: "Synergize Impactful Bandwidth",
        companyEmail: "weissnat.annetta@willms.com",
        ein: "47-8280284",
        jobTitle: "React Native Developer",
        jobDescription: [
            "Support the entire application lifecycle (concept, design, test, release and support)" ,
            "Produce fully functional mobile applications writing clean code" ,
            "Gather specific requirements and suggest solution" ,
            "Write unit and UI tests to identify malfunctions",
            "Troubleshoot and debug to optimize performance",
            "Design interfaces to improve user experience",
            "Liaise with Product development team to plan new features",
            ],
        skills: [
            "Proven work experience as a Mobile developer",
            "Demonstrable portfolio of released applications on the App store or the Android market",
            "In-depth knowledge of at least one programming language like Swift and Java",
            "Experience with third-party libraries and APIs",
            "Familiarity with OOP design principles",
            "Excellent analytical skills with a good problem-solving attitude",
            ],
        category: "Mobile Development",
        jobSnippet: "We are looking for someone who can maintain our Mobile app development needs and be involved in solving blockchain based problems.",
        employmentStatus: "Full-time",
        salary: 29000,
        aor: "Office Base",
    },
];

export default JobList